title: Prerak Bhavsar
description: Law Clerk & Paralegal | Corporate, Litigation & Immigration Law | Expertise in Document Administration (Clio, iManage) | Delivering Seamless Legal Operations & File Management Across Canada
#show_downloads: false
theme: jekyll-theme-minimal
