title: Prerak Bhavsar
description: Corporate Associate @ Khaitan & Co. | Cross-Border Legal Advisory | Corporate Law, Contract Management & Legal Operations
#show_downloads: false
theme: jekyll-theme-minimal
